#!/bin/bash
clear
echo "
           __ _____    __  __  _____  _      __    __    __  __  
 /\ /\  /\ \ \\\\_   \/\ \ \/ _\/__   \/_\    / /   / /   /__\/__\ 
/ / \ \/  \/ / / /\/  \/ /\ \   / /\//_\\\\  / /   / /   /_\ / \// 
\ \_/ / /\  /\/ /_/ /\  / _\ \ / / /  _  \/ /___/ /___//__/ _  \ 
 \___/\_\ \/\____/\_\ \/  \__/ \/  \_/ \_/\____/\____/\__/\/ \_/                                                                 
";

echo "[*] - Looking for current install...";

if [ "$PREFIX" = "/data/data/com.termux/files/usr" ]; then
    INSTALL_DIR="$PREFIX/usr/share/doc/onifw"
    BIN_DIR="$PREFIX/bin/"
    BASH_PATH="$PREFIX/bin/bash"
    TERMUX=true

else
    INSTALL_DIR="$HOME/.onifw/"
    BIN_DIR="/usr/local/bin/"
    BASH_PATH="/bin/bash"
    TERMUX=false

fi

if [ "$TERMUX" = true ]; then
    rm -rf "$ETC_DIR/w0bos"
    rm -rf "$INSTALL_DIR"
    rm -rf "$BIN_DIR/onifw"

elif [ "$TERMUX" = false ]; then
    sudo rm -rf "$INSTALL_DIR"
fi

echo "[*] - onifw was sucessfully uninstalled.";
exit
